const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  onBoot: (cb) => ipcRenderer.on('boot', (_e, data) => cb(data)),
  onUi: (cb) => ipcRenderer.on('ui-state', (_e, data) => cb(data)),
  onNeedLock: (cb) => ipcRenderer.on('need-lock', () => cb()),
  onOpenSettings: (cb) => ipcRenderer.on('open-settings', (_e, tab) => cb(tab)),
  onAskRename: (cb) => ipcRenderer.on('ask-rename', (_e, payload) => cb(payload)),
  onAskDelete: (cb) => ipcRenderer.on('ask-delete', (_e, id) => cb(id)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (_e, data) => cb(data)),
  getUi: () => ipcRenderer.invoke('get-ui'),
  switchInstance: (id) => ipcRenderer.send('switch-instance', id),
  setOverlay: (open) => ipcRenderer.send('set-overlay', open),
  addInstance: (payload) => ipcRenderer.send('add-instance', payload),
  removeInstance: (id) => ipcRenderer.send('remove-instance', id),
  renameInstance: (instanceId, label) => ipcRenderer.send('rename-instance', { instanceId, label }),
  createFolder: (name) => ipcRenderer.send('create-folder', name),
  renameFolder: (folderId, name) => ipcRenderer.send('rename-folder', { folderId, name }),
  toggleFolder: (id) => ipcRenderer.send('toggle-folder', id),
  moveToFolder: (instanceId, folderId) => ipcRenderer.send('move-to-folder', { instanceId, folderId }),
  deleteFolder: (id) => ipcRenderer.send('delete-folder', id),
  stackItems: (a, b) => ipcRenderer.send('stack-items', { a, b }),
  reorderItem: (draggedId, targetId) => ipcRenderer.send('reorder-item', { draggedId, targetId }),
  newTab: (instanceId, url) => ipcRenderer.send('new-tab', url ? { instanceId, url } : instanceId),
  toggleBookmark: (title, url) => ipcRenderer.send('toggle-bookmark', { title, url }),
  renameBookmark: (id, title) => ipcRenderer.send('rename-bookmark', { id, title }),
  openBookmark: (url, newTab) => ipcRenderer.send('open-bookmark', { url, newTab: !!newTab }),
  bookmarkMenu: (id) => ipcRenderer.send('bookmark-menu', id),
  bookmarksBarMenu: () => ipcRenderer.send('bookmarks-bar-menu'),
  toggleBookmarksBar: () => ipcRenderer.send('toggle-bookmarks-bar'),
  toggleMute: (instanceId, tabId) => ipcRenderer.send('toggle-mute', { instanceId, tabId }),
  onTabAudio: (cb) => ipcRenderer.on('tab-audio', (_e, data) => cb(data)),
  setRightPanel: (px) => ipcRenderer.send('set-right-panel', px),
  walletGetActivity: (instanceId) => ipcRenderer.invoke('wallet-get-activity', instanceId),
  walletClearActivity: (instanceId) => ipcRenderer.invoke('wallet-clear-activity', instanceId),
  onWalletActivity: (cb) => ipcRenderer.on('wallet-activity', (_e, data) => cb(data)),
  onShortcut: (cb) => ipcRenderer.on('shortcut', (_e, name) => cb(name)),
  closeTab: (instanceId, tabId) => ipcRenderer.send('close-tab', { instanceId, tabId }),
  switchTab: (instanceId, tabId) => ipcRenderer.send('switch-tab', { instanceId, tabId }),
  navigate: (instanceId, tabId, url) => ipcRenderer.send('navigate', { instanceId, tabId, url }),
  navBack: (instanceId, tabId) => ipcRenderer.send('nav-back', { instanceId, tabId }),
  navForward: (instanceId, tabId) => ipcRenderer.send('nav-forward', { instanceId, tabId }),
  navReload: (instanceId, tabId) => ipcRenderer.send('nav-reload', { instanceId, tabId }),
  onTabNavUpdate: (cb) => ipcRenderer.on('tab-nav-update', (_e, data) => cb(data)),
  accountMenu: (id) => ipcRenderer.send('account-menu', id),
  folderMenu: (id) => ipcRenderer.send('folder-menu', id),
  setPassword: (current, next) => ipcRenderer.invoke('set-password', { current, next }),
  disablePassword: (current) => ipcRenderer.invoke('disable-password', current),
  unlock: (password) => ipcRenderer.invoke('unlock', password),
  lockNow: () => ipcRenderer.send('lock-now'),
  saveSettings: (s) => ipcRenderer.send('save-settings', s),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  downloadUpdate: (url) => ipcRenderer.invoke('download-update', url),
  applyUpdate: () => ipcRenderer.invoke('apply-update'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  ping: () => ipcRenderer.send('user-activity'),
  walletGetState: (instanceId) => ipcRenderer.invoke('wallet-get-state', instanceId),
  walletImportKey: (instanceId, pk) => ipcRenderer.invoke('wallet-import-key', { instanceId, pk }),
  walletRemove: (instanceId) => ipcRenderer.invoke('wallet-remove', instanceId),
  walletRevealKey: (instanceId) => ipcRenderer.invoke('wallet-reveal-key', instanceId),
  walletSetChain: (instanceId, chainId) => ipcRenderer.invoke('wallet-set-chain', { instanceId, chainId }),
  walletSetAutoSign: (instanceId, chainId, value) => ipcRenderer.invoke('wallet-set-autosign', { instanceId, chainId, value }),
  walletSetGasCap: (instanceId, gwei) => ipcRenderer.invoke('wallet-set-gascap', { instanceId, gwei }),
  walletIsTestnet: (instanceId, chainId) => ipcRenderer.invoke('wallet-is-testnet', { instanceId, chainId }),
  onWalletConfirmRequest: (cb) => ipcRenderer.on('wallet-confirm-request', (_e, data) => cb(data)),
  walletConfirmResponse: (id, approved) => ipcRenderer.send('wallet-confirm-response', { id, approved }),
});
