const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  onBoot: (cb) => ipcRenderer.on('boot', (_e, data) => cb(data)),
  onUi: (cb) => ipcRenderer.on('ui-state', (_e, data) => cb(data)),
  onNeedLock: (cb) => ipcRenderer.on('need-lock', () => cb()),
  onOpenSettings: (cb) => ipcRenderer.on('open-settings', (_e, tab) => cb(tab)),
  onAskRename: (cb) => ipcRenderer.on('ask-rename', (_e, payload) => cb(payload)),
  getUi: () => ipcRenderer.invoke('get-ui'),
  switchInstance: (id) => ipcRenderer.send('switch-instance', id),
  setOverlay: (open) => ipcRenderer.send('set-overlay', open),
  addInstance: (payload) => ipcRenderer.send('add-instance', payload),
  removeInstance: (id) => ipcRenderer.send('remove-instance', id),
  renameInstance: (instanceId, label) => ipcRenderer.send('rename-instance', { instanceId, label }),
  createFolder: (name) => ipcRenderer.send('create-folder', name),
  renameFolder: (folderId, name) => ipcRenderer.send('rename-folder', { folderId, name }),
  toggleFolder: (id) => ipcRenderer.send('toggle-folder', id),
  moveToFolder: (instanceId, folderId) => ipcRenderer.send('move-to-folder', { instanceId, folderId }),
  deleteFolder: (id) => ipcRenderer.send('delete-folder', id),
  stackItems: (a, b) => ipcRenderer.send('stack-items', { a, b }),
  accountMenu: (id) => ipcRenderer.send('account-menu', id),
  folderMenu: (id) => ipcRenderer.send('folder-menu', id),
  setPassword: (current, next) => ipcRenderer.invoke('set-password', { current, next }),
  disablePassword: (current) => ipcRenderer.invoke('disable-password', current),
  unlock: (password) => ipcRenderer.invoke('unlock', password),
  lockNow: () => ipcRenderer.send('lock-now'),
  saveSettings: (s) => ipcRenderer.send('save-settings', s),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  downloadUpdate: (url) => ipcRenderer.invoke('download-update', url),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  ping: () => ipcRenderer.send('user-activity'),
});
