const I18N = {
  fa: { add: 'افزودن', lock: 'قفل', settings: 'تنظیمات', help: 'راهنما', rename: 'تغییر نام', remove: 'حذف اکانت', outFolder: 'خارج از پوشه', renameFolder: 'تغییر نام پوشه', deleteFolder: 'حذف پوشه', newName: 'نام جدید', save: 'ذخیره', cancel: 'انصراف', password: 'رمز عبور', currentPass: 'رمز فعلی', newPass: 'رمز جدید', savePass: 'ذخیره رمز', offPass: 'خاموش کردن قفل', lockNow: 'قفل کردن همین حالا', autoLock: 'قفل خودکار', off: 'خاموش', m1: '۱ دقیقه', m10: '۱۰ دقیقه', m30: '۳۰ دقیقه', h1: '۱ ساعت', h6: '۶ ساعت', language: 'زبان', notifications: 'اعلان‌ها', version: 'نسخه نصب‌شده', update: 'بررسی بروزرسانی', latest: 'آخرین نسخه نصب است', newer: 'نسخه جدید موجود است', about: 'درباره', donate: 'کپی آدرس دونیت', copied: 'کپی شد', enterPass: 'رمز عبور را وارد کنید', badPass: 'رمز اشتباه است', customUrl: 'آدرس سفارشی (https)', displayName: 'نام نمایشی', newFolder: 'پوشه جدید', confirmDel: 'حذف شود؟ نشست لاگین پاک می‌شود.' },
  en: { add: 'Add', lock: 'Lock', settings: 'Settings', help: 'Help', rename: 'Rename', remove: 'Remove account', outFolder: 'Remove from folder', renameFolder: 'Rename folder', deleteFolder: 'Delete folder', newName: 'New name', save: 'Save', cancel: 'Cancel', password: 'Password', currentPass: 'Current password', newPass: 'New password', savePass: 'Save password', offPass: 'Disable lock', lockNow: 'Lock now', autoLock: 'Auto-lock', off: 'Off', m1: '1 minute', m10: '10 minutes', m30: '30 minutes', h1: '1 hour', h6: '6 hours', language: 'Language', notifications: 'Notifications', version: 'Installed version', update: 'Check for updates', latest: 'Latest version is installed', newer: 'A newer version is available', about: 'About', donate: 'Copy donate address', copied: 'Copied', enterPass: 'Enter password', badPass: 'Wrong password', customUrl: 'Custom URL (https)', displayName: 'Display name', newFolder: 'New folder', confirmDel: 'Delete? Login session will be cleared.' }
};
I18N.ar = I18N.fa; I18N.tr = I18N.en; I18N.zh = I18N.en;
function t(key) {
  const lang = (window.__lang || 'fa');
  return (I18N[lang] && I18N[lang][key]) || I18N.fa[key] || key;
}
const RTL = { fa: true, ar: true, en: false, tr: false, zh: false };
